export { default as Home} from './home'
export { default as About} from './about'
export { default as Portfolio} from './portfolio'
export { default as Blog} from './blog'
export { default as BlogContent} from './blog-content'