export const GET_ABOUT_DATA = "GET_ABOUT_DATA"
export const SET_CURSOR_TEXT = "SET_CURSOR_TEXT"
export const SET_CURSOR_VARIANT = "SET_CURSOR_VARIANT"
export const SET_CURSOR_IMAGE = "SET_CURSOR_IMAGE"